/* Generated by lucy_config_generator — do not edit. */
#include "constant.h"
#include "joint.h"
#include "board.h"

const board_t boardtmp = {2};

void dump_config(void) {
  memset(boards, 0, sizeof(boards));

  board_t *internal = &boards[0];
  internal->init = &internal_init;
  internal->on_joint_subscriber_update = &internal_on_joint_subscriber_update;
  internal->on_sensor_timer_tick = &internal_on_sensor_timer_tick;

  board_t *adafruit = ++internal;
  adafruit->pin.i2c.sda = INTERNAL_I2C_SDA;
  adafruit->pin.i2c.scl = INTERNAL_I2C_SCL;
  adafruit->pin.i2c.port = INTERNAL_I2C_PORT;
  adafruit->init = &adafruit_init;
  adafruit->on_joint_subscriber_update = &adafruit_on_joint_subscriber_update;

  joint_t *joint = internal->data.internal.joints;


  joint = adafruit->data.adafruit.joints;
}