/* Generated by lucy_config_generator — do not edit. */
#include "constant.h"
#include "joint.h"
#include "board.h"

void dump_config(void) {
  memset(boards, 0, sizeof(boards));

  board_t *board = &boards[0];
  board->init = &internal_init;
  board->on_joint_subscriber_update = &internal_on_joint_subscriber_update;

  joint_t *joint = board->data.internal.joints;

  /* right_shoulder_z */
  joint->config.virtual_pin =         0;
  joint->config.physical_pin =        INTERNAL_SERVO_10;
  joint->config.servo_type =          SERVO_TYPE_270;
  joint->config.security_min_angle =  DEG_TO_RAD(155.0);
  joint->config.security_max_angle =  DEG_TO_RAD(165.0);
  joint->config.default_angle =       DEG_TO_RAD(160.0);
  joint->config.init_joint =          &internal_joint_init;
  joint->config.move_joint =          &internal_joint_move;
  joint++;
  /* right_shoulder_x */
  joint->config.virtual_pin =         1;
  joint->config.physical_pin =        INTERNAL_SERVO_11;
  joint->config.servo_type =          SERVO_TYPE_270;
  joint->config.security_min_angle =  DEG_TO_RAD(140.0);
  joint->config.security_max_angle =  DEG_TO_RAD(180.0);
  joint->config.default_angle =       DEG_TO_RAD(180.0);
  joint->config.init_joint =          &internal_joint_init;
  joint->config.move_joint =          &internal_joint_move;
  joint++;
  /* right_elbow */
  joint->config.virtual_pin =         2;
  joint->config.physical_pin =        INTERNAL_SERVO_12;
  joint->config.servo_type =          SERVO_TYPE_270;
  joint->config.security_min_angle =  DEG_TO_RAD(100.0);
  joint->config.security_max_angle =  DEG_TO_RAD(110.0);
  joint->config.default_angle =       DEG_TO_RAD(100.0);
  joint->config.init_joint =          &internal_joint_init;
  joint->config.move_joint =          &internal_joint_move;
  joint++;
  /* right_wrist_z */
  joint->config.virtual_pin =         3;
  joint->config.physical_pin =        INTERNAL_SERVO_13;
  joint->config.servo_type =          SERVO_TYPE_300;
  joint->config.security_min_angle =  DEG_TO_RAD(0.0);
  joint->config.security_max_angle =  DEG_TO_RAD(230.0);
  joint->config.default_angle =       DEG_TO_RAD(150.0);
  joint->config.init_joint =          &internal_joint_init;
  joint->config.move_joint =          &internal_joint_move;
  joint++;
  /* right_thumb */
  joint->config.virtual_pin =         4;
  joint->config.physical_pin =        INTERNAL_SERVO_14;
  joint->config.servo_type =          SERVO_TYPE_300;
  joint->config.security_min_angle =  DEG_TO_RAD(36.0);
  joint->config.security_max_angle =  DEG_TO_RAD(150.0);
  joint->config.default_angle =       DEG_TO_RAD(36.0);
  joint->config.init_joint =          &internal_joint_init;
  joint->config.move_joint =          &internal_joint_move;
  joint++;
  /* right_index */
  joint->config.virtual_pin =         5;
  joint->config.physical_pin =        INTERNAL_SERVO_15;
  joint->config.servo_type =          SERVO_TYPE_300;
  joint->config.security_min_angle =  DEG_TO_RAD(16.0);
  joint->config.security_max_angle =  DEG_TO_RAD(150.0);
  joint->config.default_angle =       DEG_TO_RAD(16.0);
  joint->config.init_joint =          &internal_joint_init;
  joint->config.move_joint =          &internal_joint_move;
  joint++;
  /* right_majeure */
  joint->config.virtual_pin =         6;
  joint->config.physical_pin =        INTERNAL_SERVO_16;
  joint->config.servo_type =          SERVO_TYPE_300;
  joint->config.security_min_angle =  DEG_TO_RAD(21.0);
  joint->config.security_max_angle =  DEG_TO_RAD(150.0);
  joint->config.default_angle =       DEG_TO_RAD(21.0);
  joint->config.init_joint =          &internal_joint_init;
  joint->config.move_joint =          &internal_joint_move;
  joint++;
  /* right_ring */
  joint->config.virtual_pin =         7;
  joint->config.physical_pin =        INTERNAL_SERVO_17;
  joint->config.servo_type =          SERVO_TYPE_300;
  joint->config.security_min_angle =  DEG_TO_RAD(33.0);
  joint->config.security_max_angle =  DEG_TO_RAD(150.0);
  joint->config.default_angle =       DEG_TO_RAD(33.0);
  joint->config.init_joint =          &internal_joint_init;
  joint->config.move_joint =          &internal_joint_move;
  joint++;
  /* right_pinky */
  joint->config.virtual_pin =         8;
  joint->config.physical_pin =        INTERNAL_SERVO_18;
  joint->config.servo_type =          SERVO_TYPE_300;
  joint->config.security_min_angle =  DEG_TO_RAD(30.0);
  joint->config.security_max_angle =  DEG_TO_RAD(150.0);
  joint->config.default_angle =       DEG_TO_RAD(30.0);
  joint->config.init_joint =          &internal_joint_init;
  joint->config.move_joint =          &internal_joint_move;
  joint++;
}