/* Generated by lucy_config_generator — do not edit. */
#include "constant.h"
#include "joint.h"
#include "board.h"

void dump_config(void) {
  memset(boards, 0, sizeof(boards));

  board_t *board = &boards[0];
  board->init = &internal_init;
  board->on_joint_subscriber_update = &internal_on_joint_subscriber_update;

  joint_t *joint = board->data.internal.joints;

}